baseURL = "https://hardcode.blog/"
languageCode = "en-en"
title = "HARDCODE.blog"

paginate = 5

copyright = "¬© Copyright Francesco Bianco"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-178422206-1"
disqusShortname = "hardcode-blog"

[params]
subtitle = "{‚òï} Coding, the superpower that no one to want to have"

# Optional 64x64 avatar image.
avatar = "/images/logo.png"

# Content types to disable Disqus on.
disableDisqusTypes = ["page"]

featherIconsCDN = true

mode = "auto"
# "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
#[[menu.main]]
#name = "üçï"
#url = "/pizza"
#weight = 1

[[menu.main]]
name = "Home"
url = "/"
weight = 2

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 3

[[menu.main]]
name = "Docker"
url = "/tags/docker"
weight = 4

[[menu.main]]
name = "Vtiger"
url = "/tags/vtiger"
weight = 5

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 6

[[menu.main]]
name = "About"
url = "/about"
weight = 7

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/francescobianco/hardcode.blog"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/francescobianco"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
tag = "tags"
