baseURL = "https://hardcode.blog/"
languageCode = "en-en"
title = "HARDCODE.BLOG"

paginate = 4

copyright = "Â© Francesco Bianco"

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true
pygmentsCodefences = true

#googleAnalytics = "UA-178422206-1"
disqusShortname = "hardcode-blog"

[params]
subtitle = "{â˜•} Coding, the superpower that nobody wants to have."

# Optional 64x64 avatar image.
avatar = "/images/logo.png"

# Content types to disable Disqus on.
disableDisqusTypes = ["page"]

featherIconsCDN = true

mode = "auto"
# "dark" or "auto"
# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

repository = "https://github.com/francescobianco/hardcode.blog"

# Nav.
#[[menu.main]]
#name = "ğŸ•"
#url = "/pizza"
#weight = 1

[[menu.main]]
name = "ğŸ  Home"
url = "/"
weight = 2

#[[menu.main]]
#name = "All posts"
#url = "/posts"
#weight = 3

[[menu.main]]
name = "ğŸ³ Docker"
url = "/tags/docker"
weight = 4

[[menu.main]]
name = "ğŸ¯ Vtiger"
url = "/tags/vtiger"
weight = 5

[[menu.main]]
name = "ğŸ·ï¸ Tags"
url = "/tags"
weight = 6

[[menu.main]]
name = "ğŸ‘· About"
url = "/about"
weight = 7

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/francescobianco"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/yafb"

[[params.social]]
name = "YouTube"
icon = "youtube"
url = "https://www.youtube.com/@yafb/"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/index.xml"

[taxonomies]
author = "authors"
tag = "tags"

[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'monokai'
tabWidth = 4
